### PR TITLE
Fix double-quoting of `verbose` arg in S3 backend

### LINKED ISSUE #47: `BUILDKITE_PLUGIN_S3_CACHE_ONLY_SHOW_ERRORS` must be set
At the moment, the following error is produced when using the AWS CLI v1 with the `s3` backend, unless `BUILDKITE_PLUGIN_S3_CACHE_ONLY_SHOW_ERRORS` is set:

image

I think this is because of the double quotes around the `"$(verbose)"` argument in `save_cache` and `restore_cache`, which forces the argument to be interpreted as an empty option string.

### PR DESCRIPTION
**Pull request by DavidGregory084**
Fixes #47.

### CODE REVIEW

**Review by toote — CHANGES_REQUESTED** [review]
Unfortunately this causes shellcheck to complain about the missing quotes.

I do agree that this need fixed, though... but the correct way to do it may be to replace the `verbose` function with something like the following:

```bash
s3_sync () {
  local from="$1"
  local to="$2"

  aws_cmd = (aws sync)
  if [ -n "${BUILDKITE_PLUGIN_S3_CACHE_ONLY_SHOW_ERRORS}" ]; then
    aws_cmd += (--only-show-errors)
  fi

  "$@" "$from" "$to"
}
```
and then update the `restore_cache` and `save_cache` functions to use that instead of running the command directly

**Comment by DavidGregory084** [comment]
Oh I see, I had hoped that the `# shellcheck disable=SC2046` comment would be respected by the linter!

**Comment by toote** [comment]
@DavidGregory084 actually, it would... but I find that disabling shellchecks can be detrimental when alternative implementations can be achieved without disabling any checks

**Comment by HugeIRL** [comment]
Solved by: https://github.com/buildkite-plugins/cache-buildkite-plugin/pull/49

**Comment by HugeIRL** [comment]
@DavidGregory084 thank you for the effort and appreciate the initial work on this. :)

**Pull request closed without merging**
