### PR TITLE
s3 backend sync

### LINKED ISSUE #52: S3 backend fails to sync with `tgz` compression
The S3 backend is unable to sync when using `tgz` compression:

image

I think this is because the `s3 sync` command does not expect to receive a single file as argument, so it tries to find a directory with the same name instead. Perhaps it should create a temporary directory in /tmp and archive a .tgz file named after the cache key into that temporary directory instead, i.e. 

```bash
ACTUAL_PATH="$(mktemp -d)"
"${COMPRESS_COMMAND[@]}" "${ACTUAL_PATH}/${KEY}.tgz" "${CACHE_PATH}"
```

I was able to replicate this on the build agent host manually:

```bash
$ ACTUAL_PATH=$(mktemp)
$ echo $ACTUAL_PATH 
/tmp/tmp.WUc3AxyL2d
$ tar czf "$ACTUAL_PATH" .gradle
$ aws s3 sync --endpoint-url "https://data.mina-lang.org" "$ACTUAL_PATH" "s3://buildkite-cache/test-key"          
warning: Skipping file /tmp/tmp.WUc3AxyL2d/. File does not exist.
```

The pipeline YAML can be viewed [here](https://codeberg.org/mina-lang/mina/src/commit/e321ed0d8a3a22894910cf708e764f8bbdf67678/.buildkite/pipeline.yml).

You can view a gist of a build log exhibiting this problem [here](https://gist.github.com/DavidGregory084/bf17b49962cf524e7f01ac27eb9f8aba).

One other thing that I noticed in this log is that the second cache post-command hook did not run after the first one failed. Is that expected?

### PR DESCRIPTION
**Pull request by toote**
As reported in #52, `aws s3 sync` does not work well with single files. This is a general issue but particularly troublesome when using compression as that will always be the case. What's more, restoring off S3 may have the exact same issue so I have changed restoring to always use `cp --recursive` and the cache saving to use `sync` by default, but if it is a file use `cp` instead.

Different to #53, this change is exclusive to the S3 backend so other backends should not be affected as it did not change the protocol. That said, it would be great to get a lot of testing on it :)

Closes #52

### CODE REVIEW

**Review by tomowatt — APPROVED** [review]
Looks good to me

**Comment by geoffharcourt** [comment]
Hi, we are still seeing this kind of error when using `tgz` compression and syncing with S3 on v1.0.0:

This is our plugin configuration:

```yaml
      - cache#v1.0.0:
          backend: s3
          compression: tgz # does not fail if compression is off
          manifest: Gemfile.lock
          path: /bundle
          restore: pipeline
          save: file
```


```
$ /var/lib/buildkite-agent/plugins/buildkite-2024-01-v1-i-0dd6e48437206d62e-1/github-com-buildkite-plugins-cache-buildkite-plugin-v1-0-0/hooks/post-command
Compressing /bundle with tgz...
tar: Removing leading `/' from member names
Saving file-level cache of /bundle
warning: Skipping file /tmp/tmp.ljlvBP6i63/. File does not exist.
🚨 Error: The plugin cache post-command hook exited with status 2
```

We do not see errors when compression is turned off (it just takes a really long time to run because of the number of files/objects).

**Comment by smsunarto** [comment]
+1 still seeing this issue

**Comment by toote** [comment]
@geoffharcourt @smsunarto I have created a new PR #65 that I believe should solve the issue but would love your input on it

**Pull request merged**
